### ISSUE TITLE
Unable to connect to SFMC behind the Firewall

### ISSUE THREAD

**Issue by VasaK** [mulesoft/mulesoft-docs-build-output#1]
We are trying to connect to SFMC instance using Marketing colud connector (org.mule.tooling.ui.contribution.sfdc-marketing-cloud.3.5.0)  provided in community version. The connector unable to get pass Firewall and the connector doesn't have way to provide proxy details.  Any help is appreciated.

Here is how connector is configured.

<sfdc-marketing-cloud:config name="Salesforce_Marketing_Cloud__Configuration" username="${sfmc.user}" password="${sfmc.password}" endpoint="${sfmc.url}" doc:name="Salesforce Marketing Cloud: Configuration"/>

Thank you
Vasa

**Comment by sharkberto** [comment]
VasaK this is the html output repo, let us know if any trouble on mulesoft-docs repo https://github.com/mulesoft/mulesoft-docs
